### ISSUE TITLE
Add tests for HexBuilder

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/yoko#151]
Write new tests for the already existing functions within the Testify framework.

Recommend using Cucumber (Gherkin) Full Support to check the test coverage.

**Comment by SimonaStavarache** [comment]
Packages to be tested: 
yoko-testify/src/main/java/testify/bus
yoko-testify/src/main/java/testify/expect
yoko-testify/src/main/java/testify/io
yoko-testify/src/main/java/testify/jupiter/annotation
yoko-testify/src/main/java/testify/jupiter/annotation/impl
yoko-testify/src/main/java/testify/jupiter/annotation/logging
yoko-testify/src/main/java/testify/matchers
yoko-testify/src/main/java/testify/streams
